# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageid', models.CharField(max_length=32, unique=True, verbose_name='镜像ID')),
                ('os', models.CharField(max_length=64, verbose_name='操作系统')),
                ('size', models.IntegerField(verbose_name='镜像大小')),
                ('type', models.CharField(max_length=64, verbose_name='镜像类型')),
                ('state', models.CharField(max_length=32, verbose_name='镜像状态')),
                ('source', models.CharField(max_length=32, verbose_name='镜像源')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='ProductCode')),
                ('name', models.CharField(max_length=64, verbose_name='镜像名')),
                ('des', models.CharField(max_length=64, verbose_name='镜像描述')),
                ('init', models.BooleanField(default=False, verbose_name='是否初始化')),
                ('platform', models.CharField(max_length=32, verbose_name='系统类型')),
                ('arch', models.CharField(max_length=32, verbose_name='系统位数')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.CharField(blank=True, max_length=50, null=True, verbose_name='最近一次更新时间')),
            ],
            options={
                'verbose_name': '镜像',
                'verbose_name_plural': '镜像',
            },
        ),
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(max_length=32, verbose_name='所在位置')),
                ('project', models.CharField(max_length=32, verbose_name='项目')),
                ('instance_id', models.CharField(max_length=64, unique=True, verbose_name='实例ID')),
                ('instancestate', models.CharField(choices=[('PENDING', '在创建'), ('RUNNING', '在运行'), ('STOPPED', '关机'), ('STARTING', '在开机'), ('STOPPING', '在关机'), ('REBOOTING', '在重启')], max_length=32, verbose_name='实例运行状态')),
                ('restrictstate', models.CharField(choices=[('NORMAL', '正常状态'), ('EXPIRED', '已过期'), ('PROTECTIVELY_ISOLATED', '已被隔离')], default='NORMAL', max_length=32, verbose_name='实例业务状态')),
                ('type', models.CharField(max_length=32, verbose_name='实例机型')),
                ('cpu', models.IntegerField(verbose_name='CPU核数/核')),
                ('memory', models.SmallIntegerField(verbose_name='内存/G')),
                ('name', models.CharField(max_length=32, verbose_name='实例名称')),
                ('systemdisk', models.CharField(max_length=128, verbose_name='系统盘信息')),
                ('datadisk', models.CharField(blank=True, max_length=128, null=True, verbose_name='数据盘信息')),
                ('nip', models.GenericIPAddressField(verbose_name='内网地址')),
                ('wip', models.GenericIPAddressField(verbose_name='公网地址')),
                ('bandwith', models.CharField(max_length=64, verbose_name='带宽信息')),
                ('securityid', models.CharField(max_length=32, verbose_name='安全组')),
                ('image', models.CharField(max_length=32, verbose_name='镜像')),
                ('os', models.CharField(max_length=32, verbose_name='操作系统')),
                ('renewflag', models.CharField(choices=[('NOTIFY_AND_MANUAL_RENEW', '要过期不续费'), ('NOTIFY_AND_AUTO_RENEW', '要过期自动续费'), ('DISABLE_NOTIFY_AND_MANUAL_RENEW', '不通知过期续费')], max_length=32, verbose_name='自动续费标识')),
                ('ctime', models.CharField(max_length=64, verbose_name='创建时间')),
                ('etime', models.CharField(max_length=64, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '实例信息',
                'verbose_name_plural': '实例信息',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32, unique=True, verbose_name='Region')),
                ('name', models.CharField(max_length=64, verbose_name='RegionName')),
                ('state', models.CharField(choices=[('AVAILABLE', '可用'), ('UNAVAILABLE', '不可用')], max_length=32, verbose_name='RegionState')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.CharField(blank=True, max_length=50, null=True, verbose_name='最近一次更新时间')),
            ],
            options={
                'verbose_name': 'Region列表',
                'verbose_name_plural': 'Region列表',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone', models.CharField(max_length=64, unique=True, verbose_name='Zone')),
                ('name', models.CharField(max_length=64, verbose_name='ZoneName')),
                ('zid', models.IntegerField(primary_key=True, serialize=False, verbose_name='ZoneId')),
                ('state', models.CharField(choices=[('AVAILABLE', '可用'), ('UNAVAILABLE', '不可用')], max_length=32, verbose_name='ZoneState')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.CharField(blank=True, max_length=50, null=True, verbose_name='最近一次更新时间')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Zone列表',
                'verbose_name_plural': 'Zone列表',
            },
        ),
        migrations.AddField(
            model_name='instances',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='image',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Region', verbose_name='region'),
        ),
    ]
