# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstancesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=32, verbose_name='可用区')),
                ('family', models.CharField(max_length=32, verbose_name='实例机型系列')),
                ('type', models.CharField(max_length=32, verbose_name='实例机型')),
                ('cpu', models.IntegerField(verbose_name='CPU')),
                ('gpu', models.IntegerField(verbose_name='GPU')),
                ('fpga', models.IntegerField(verbose_name='FPGA')),
                ('memory', models.IntegerField(verbose_name='内存')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Region', verbose_name='大区ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, verbose_name='大区名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=32, unique=True, verbose_name='大区ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=64, verbose_name='可用区名'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Region', verbose_name='大区ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='可用区ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone',
            field=models.CharField(max_length=64, unique=True, verbose_name='可用区'),
        ),
        migrations.AddField(
            model_name='instancestype',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Region', verbose_name='大区ID'),
        ),
    ]
