# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20181207_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancestype',
            options={'verbose_name': '实例机型', 'verbose_name_plural': '实例机型'},
        ),
        migrations.AlterUniqueTogether(
            name='instancestype',
            unique_together=set([('family', 'type')]),
        ),
    ]
