# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20181207_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancestype',
            name='fpga',
        ),
        migrations.RemoveField(
            model_name='instancestype',
            name='gpu',
        ),
    ]
