# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20181207_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='chargetype',
            field=models.CharField(choices=[('PREPAID', '预付费'), ('POSTPAID_BY_HOUR', '后付费'), ('CDHPAID', 'CDH付费')], default='PREPAID', max_length=32, verbose_name='实例计费模式'),
        ),
    ]
