# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_instances_chargetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageid',
            field=models.CharField(max_length=32, verbose_name='镜像ID'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('region', 'imageid')]),
        ),
    ]
