# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessunit', to='assets.BusinessUnit', verbose_name='业务线'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idc', to='assets.IDC', verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='assets.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='描述'),
        ),
    ]
