# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181109_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='server_type',
            field=models.CharField(choices=[('physical', '物理机'), ('virtual', '虚拟机'), ('instance', '云主机')], default='instance', max_length=10, verbose_name='服务器类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(choices=[('online', '上线'), ('offline', '下线')], default='offline', max_length=10, verbose_name='状态'),
        ),
    ]
