# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181114_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
