# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181118_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='nip',
            field=models.GenericIPAddressField(error_messages={'blank': 'NIP不能为空', 'invalid': 'NIP地址格式错误', 'unique': '该NIP已存在，请不要重复添加'}, unique=True, verbose_name='内网地址'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='wip',
            field=models.GenericIPAddressField(error_messages={'blank': 'WIP不能为空', 'invalid': 'WIP地址格式错误', 'unique': '该WIP已存在，请不要重复添加'}, unique=True, verbose_name='外网地址'),
        ),
    ]
