# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_businessunit_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='机房名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色'),
        ),
    ]
