# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181115_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(error_messages={'unique': '该机房已存在，请不要重复添加'}, max_length=64, unique=True, verbose_name='机房名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'unique': '该角色已存在，请不要重复添加'}, max_length=32, unique=True, verbose_name='角色'),
        ),
    ]
