# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20181116_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='hostname',
            field=models.CharField(error_messages={'unique': '该主机名已存在，请不要重复添加'}, max_length=32, unique=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='nip',
            field=models.GenericIPAddressField(blank=True, error_messages={'invalid': 'IP地址格式错误', 'unique': '该IP已存在，请不要重复添加'}, null=True, unique=True, verbose_name='内网地址'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='wip',
            field=models.GenericIPAddressField(blank=True, error_messages={'invalid': 'IP地址格式错误', 'unique': '该IP已存在，请不要重复添加'}, null=True, unique=True, verbose_name='外网地址'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(error_messages={'unique': '该业务线已存在，请不要重复添加'}, max_length=64, unique=True, verbose_name='业务线'),
        ),
        migrations.AlterField(
            model_name='remoteuser',
            name='name',
            field=models.CharField(error_messages={'unique': '该名称已存在，请不要重复添加'}, max_length=24, unique=True, verbose_name='名称'),
        ),
    ]
