# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20181116_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='disk',
            field=models.IntegerField(default=0, verbose_name='硬盘/GB'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='memory',
            field=models.SmallIntegerField(default=0, verbose_name='内存/GB'),
        ),
    ]
