# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinionList',
            fields=[
                ('minion_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='MinionID')),
                ('ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='IP地址')),
                ('minion_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minion版本')),
                ('system_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='系统类型')),
                ('sys', models.CharField(blank=True, max_length=32, null=True, verbose_name='系统版本')),
                ('cpu_info', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU信息')),
                ('hostname', models.CharField(blank=True, max_length=200, null=True, verbose_name='主机名')),
                ('memory', models.IntegerField(blank=True, null=True, verbose_name='内存大小')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.CharField(blank=True, max_length=50, null=True, verbose_name='最近一次更新时间')),
                ('minion_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Minion状态')),
                ('des', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述备注')),
            ],
            options={
                'verbose_name': 'Minion列表',
                'verbose_name_plural': 'Minion列表',
                'ordering': ['minion_id'],
            },
        ),
        migrations.CreateModel(
            name='SaltCmdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_cmd', models.CharField(max_length=100, verbose_name='命令')),
                ('salt_cmd_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('salt_cmd_module', models.CharField(blank=True, max_length=200, null=True, verbose_name='模块')),
                ('salt_cmd_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='命令来源')),
                ('salt_cmd_doc', models.TextField(blank=True, null=True, verbose_name='命令帮助信息')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('utime', models.CharField(blank=True, max_length=50, null=True, verbose_name='最近一次采集时间')),
                ('des', models.TextField(blank=True, null=True, verbose_name='描述备注')),
            ],
            options={
                'verbose_name': 'salt命令集表',
                'verbose_name_plural': 'salt命令集表',
                'ordering': ['salt_cmd_type', 'salt_cmd'],
            },
        ),
        migrations.CreateModel(
            name='SaltKeyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_id', models.CharField(max_length=20, verbose_name='MinionID')),
                ('certification_status', models.CharField(max_length=20, verbose_name='认证状态')),
                ('utime', models.CharField(blank=True, max_length=50, null=True, verbose_name='最近一次更新时间')),
            ],
            options={
                'verbose_name': 'Salt-key信息表',
                'verbose_name_plural': 'Salt-key信息表',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='saltcmdinfo',
            unique_together=set([('salt_cmd', 'salt_cmd_type')]),
        ),
    ]
